USE DATABASE formulario;

CREATE TABLE usuarios (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR (45) NOT NULL,
email VARCHAR (110) NOT NULL,
senha VARCHAR (100) NOT NULL,
data_nasc DATE NOT NULL,
telefone VARCHAR (15) NOT NULL,
sexo VARCHAR (15) NOT NULL, 
cpf VARCHAR (11) NOT NULL,
estadocivil VARCHAR (50) NOT NULL,
estado VARCHAR (100) NOT NULL,
cidade VARCHAR (100) NOT NULL,
endereco VARCHAR (100) NOT NULL);